### ISSUE TITLE
Undefined variable: v:false

### ISSUE THREAD

**Issue by wsdjeg** [lymslive/vimloo#1]
Some people use this plugin in SpaceVim, but get errors with v:false, this value is added in latest version of vim, I think we should support old version vim.

cc @hongjiujin @angelo-chan

**Comment by lymslive** [comment]
It's really bother to fix v:false & v:true for lower version.
It make code meaningful.
vim 7.4 is OK, no need the latest vim8.0

**Comment by wsdjeg** [comment]
If you need help, I will look into it. BTW, I think we can talk more about this lib and SpaceVim's api, I want to create a oop api.
